name: Build and Deploy to Vault Repo

on:
  push:
    tags:
      - "*-v*.*.*" # This triggers the action on version tags like v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Deploy to the central showcase repo
        run: |
          # Clone the central showcase repository
          git clone https://github.com/sarahrobichaud/harborvault.git

          # Copy build output to the appropriate directory in the showcase repo

          mkdir -p haborvault/chromabay/${GITHUB_REF_NAME}
          cp -R dist/* harborvault/chromabay/${GITHUB_REF_NAME}/

          # Commit and push changes to the showcase repo
          cd harborvault
          git add .
          git commit -m "Deploy ${GITHUB_REF_NAME}"
          git push origin main
